import type { Metadata } from "next";
// Zen — the one family. @hanzo/design ships the two variable faces and declares
// their @font-face, so this app vendors no font binary and reads the family
// through the role tokens --font-sans / --font-mono.
import "@hanzo/design/tokens/fonts.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
